language: node_js
node_js: 
  - 13

services: 
  - docker

script: 
  - docker build -t feed-api .
  - docker tag feed-api emukungu/feed-api:latest

after_success: 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push emukungu/feed-api
